pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Check out the code from your GitHub repository
                git branch: 'main', url: 'https://github.com/Ankithv007/Terraform.git'
            }
        }

        stage('Build') {
            steps {
                // Build or setup Terraform (adjust as needed)
                sh 'echo "Setting up Terraform..."'
            }
        }

        stage('Test') {
            steps {
                // Run Terraform commands or any tests (adjust as needed)
                sh 'echo "Running Terraform..."'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
