variable "region"{ }
variable "project_vpc"{ }
variable "vpc_cidr"{ }
variable "cidr_block_az1" {}
variable "cidr_block_az2" {}
variable "private-cidr_block_az1" {}
variable "private-cidr_block_az2" {}
variable "private-data-subnet-cidr_block_az1" {}
variable "private-data-subnet-cidr_block_az2" {}